# Generated by Django 4.1.1 on 2022-09-26 15:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_alter_post_content'),
    ]

    operations = [
        migrations.RenameField(
            model_name='category',
            old_name='category_id',
            new_name='cat_id',
        ),
        migrations.RenameField(
            model_name='post',
            old_name='category',
            new_name='cat',
        ),
    ]
